import { Cocktail } from './cocktails-module';

export const COCKTAILS: Cocktail[] = [
    { name: 'Bangkok Denpasar', recipe: 'this is my reciept' },
    { name: 'Bitter Orange Mule', recipe: 'this is my reciept' },
    { name: 'Blue Birds Fly To London', recipe: 'this is my reciept' },
    { name: 'ButterFly', recipe: 'this is my reciept' },
    { name: 'Coconut White Rasta', recipe: 'this is my reciept' },
    { name: 'Coniferous Fores', recipe: 'this is my reciept' },
    { name: 'Cover Club Twist', recipe: 'this is my reciept' },
    { name: 'Crimson & Clover Club', recipe: 'this is my reciept' },
    { name: 'Diamond Spritz', recipe: 'this is my reciept' },
    { name: 'Fille de Berlin', recipe: 'this is my reciept' },
    { name: 'Gin Ginger Daisy', recipe: 'this is my reciept' },
    { name: 'Gin Sour Twist', recipe: 'this is my reciept' },
    { name: 'Harvey WallBanger Twist', recipe: 'this is my reciept' },
    { name: 'Ichigo Rosé', recipe: 'this is my reciept' },
    { name: 'Mosly a Northern Song', recipe: 'this is my reciept' },
    { name: 'Mr Shulze\'s Sour', recipe: 'this is my reciept' },
    { name: 'N/A', recipe: 'this is my reciept' },
    { name: 'New York Sour', recipe: 'this is my reciept' },
    { name: 'Nordic Mule', recipe: 'this is my reciept' },
    { name: 'Odyssee', recipe: 'this is my reciept' },
    { name: 'Old Fashioned', recipe: 'this is my reciept' },
    { name: 'Other Worldly', recipe: 'this is my reciept' },
    { name: 'Passion Jungle', recipe: 'this is my reciept' },
    { name: 'Pink Cosmo', recipe: 'this is my reciept' },
    { name: 'Queen\'s Park Swizzle', recipe: 'this is my reciept' },
    { name: 'Red Light District', recipe: 'this is my reciept' },
    { name: 'Risque Business', recipe: 'this is my reciept' },
    { name: 'Roku Sour', recipe: 'this is my reciept' },
    { name: 'Soa Paulo Swizzle', recipe: 'this is my reciept' },
    { name: 'Signature Style', recipe: 'this is my reciept' },
    { name: 'Silver Monk', recipe: 'this is my reciept' },
    { name: 'Smoked Dates', recipe: 'this is my reciept' },
    { name: 'Something WIth Whiskey Or Rum', recipe: 'this is my reciept' },
    { name: 'Southpaw', recipe: 'this is my reciept' },
    { name: 'Story Teller', recipe: 'this is my reciept' },
    { name: 'The Georgetown Demerare Rum Slinger', recipe: 'this is my reciept' },
    { name: 'Theo Broma', recipe: 'this is my reciept' },
    { name: 'Tiki', recipe: 'this is my reciept' },
    { name: 'Trappin In Heaven', recipe: 'this is my reciept' },
    { name: 'Tungus', recipe: 'this is my reciept' },
    { name: 'Very Supersticious', recipe: 'this is my reciept' },
    { name: 'VioletFizz', recipe: 'this is my reciept' }
];
