import { Cocktail } from './cocktails-module';

export const COCKTAILS: Cocktail[] = [
    { id: 1, name: 'Bangkok Denpasar', recipe: 'this is my reciept' },
    { id: 2, name: 'Bitter Orange Mule', recipe: 'this is my reciept' },
    { id: 3, name: 'Blue Birds Fly To London', recipe: 'this is my reciept' },
    { id: 4, name: 'ButterFly', recipe: 'this is my reciept' },
    { id: 5, name: 'Coconut White Rasta', recipe: 'this is my reciept' },
    { id: 6, name: 'Coniferous Fores', recipe: 'this is my reciept' },
    { id: 7, name: 'Cover Club Twist', recipe: 'this is my reciept' },
    { id: 8, name: 'Crimson & Clover Club', recipe: 'this is my reciept' },
    { id: 9, name: 'Diamond Spritz', recipe: 'this is my reciept' },
    { id: 10, name: 'Fille de Berlin', recipe: 'this is my reciept' },
    { id: 11, name: 'Gin Ginger Daisy', recipe: 'this is my reciept' },
    { id: 12, name: 'Gin Sour Twist', recipe: 'this is my reciept' },
    { id: 13, name: 'Harvey WallBanger Twist', recipe: 'this is my reciept' },
    { id: 14, name: 'Ichigo Rosé', recipe: 'this is my reciept' },
    { id: 15, name: 'Mosly a Northern Song', recipe: 'this is my reciept' },
    { id: 16, name: 'Mr Shulze\'s Sour', recipe: 'this is my reciept' },
    { id: 17, name: 'N/A', recipe: 'this is my reciept' },
    { id: 18, name: 'New York Sour', recipe: 'this is my reciept' },
    { id: 19, name: 'Nordic Mule', recipe: 'this is my reciept' },
    { id: 20, name: 'Odyssee', recipe: 'this is my reciept' },
    { id: 21, name: 'Old Fashioned', recipe: 'this is my reciept' },
    { id: 22, name: 'Other Worldly', recipe: 'this is my reciept' },
    { id: 23, name: 'Passion Jungle', recipe: 'this is my reciept' },
    { id: 24, name: 'Pink Cosmo', recipe: 'this is my reciept' },
    { id: 25, name: 'Queen\'s Park Swizzle', recipe: 'this is my reciept' },
    { id: 26, name: 'Red Light District', recipe: 'this is my reciept' },
    { id: 27, name: 'Risque Business', recipe: 'this is my reciept' },
    { id: 28, name: 'Roku Sour', recipe: 'this is my reciept' },
    { id: 29, name: 'Soa Paulo Swizzle', recipe: 'this is my reciept' },
    { id: 30, name: 'Signature Style', recipe: 'this is my reciept' },
    { id: 31, name: 'Silver Monk', recipe: 'this is my reciept' },
    { id: 32, name: 'Smoked Dates', recipe: 'this is my reciept' },
    { id: 33, name: 'Something WIth Whiskey Or Rum', recipe: 'this is my reciept' },
    { id: 34, name: 'Southpaw', recipe: 'this is my reciept' },
    { id: 35, name: 'Story Teller', recipe: 'this is my reciept' },
    { id: 36, name: 'The Georgetown Demerare Rum Slinger', recipe: 'this is my reciept' },
    { id: 37, name: 'Theo Broma', recipe: 'this is my reciept' },
    { id: 38, name: 'Tiki', recipe: 'this is my reciept' },
    { id: 39, name: 'Trappin In Heaven', recipe: 'this is my reciept' },
    { id: 40, name: 'Tungus', recipe: 'this is my reciept' },
    { id: 41, name: 'Very Supersticious', recipe: 'this is my reciept' },
    { id: 42, name: 'VioletFizz', recipe: 'this is my reciept' }
];
